name: Trigger auto deployment for nzaplcicdcapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/nzaplcicdcapp-AutoDeployTrigger-ea1bdd70-8f70-44c6-af10-2871225a72f7.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca46990fd1e3acr.azurecr.io
          username: ${{ secrets.NZAPLCICDCAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.NZAPLCICDCAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca46990fd1e3acr.azurecr.io/nzaplcicdcapp:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NZAPLCICDCAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n nzaplcicdcapp -g nzaplcontainerapps-rg --server ca46990fd1e3acr.azurecr.io --username  ${{ secrets.NZAPLCICDCAPP_REGISTRY_USERNAME }} --password ${{ secrets.NZAPLCICDCAPP_REGISTRY_PASSWORD }}
            az containerapp update -n nzaplcicdcapp -g nzaplcontainerapps-rg --image ca46990fd1e3acr.azurecr.io/nzaplcicdcapp:${{ github.sha }}
